name: Rizky Adhi
favicon: null
layout_spectrum: 0.12218722747638822
typography_spectrum: 0.04061392764560878
title: Personal Websites
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.11721601919271052
  lightness: 0.17692095111124218
  saturation: 0.7267727688886225
  rhythmicContrast: 0.547057100571692
purpose: []
